### ISSUE TITLE
containerize with docker

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_SPM#4]
- [x] with octave
- [ ] with matlab

**Comment by Remi-Gau** [comment]
from #154 

### TODO
- [ ] set up github action to build and push automatically to docker hub (https://github.com/marketplace/actions/build-and-push-docker-images)
- [ ] update doc
- [ ] make recipe download the submodules

---

### issues

- [ ] can the pipeline be run if launched interactively
- [ ] look into BIDS apps to see how to standardize the docker image
- [ ] make it more ligthweight
- [ ] see linked issues for more details (create a matlab image)

**Comment by Remi-Gau** [comment]
closed by https://github.com/cpp-lln-lab/CPP_SPM/commit/85f9f40f9ab9a682cb653686faa1ae60ef250a56
