### ISSUE TITLE
Docker related TODOs

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_SPM#403]
from #154 

### TODO
- [ ] set up github action to build and push automatically to docker hub (https://github.com/marketplace/actions/build-and-push-docker-images)
- [x] update doc
- [x] make recipe download the submodules

---

### issues

- [ ] can the pipeline be run if launched interactively
- [ ] look into BIDS apps to see how to standardize the docker image
- [ ] make it more ligthweight

_Originally posted by @Remi-Gau in https://github.com/cpp-lln-lab/CPP_SPM/issues/4#issuecomment-916021941_
